### ISSUE TITLE
Dyalyxir doesn't compile

### ISSUE THREAD

**Issue by AndrewDryga** [jeremyjh/dialyxir#197]
For some reason Dyalixir stopped compiling on our CI:
```
==> dialyxir
Compiling 2 files (.erl)
/usr/local/lib/erlang/lib/parsetools-2.1.7/include/yeccpre.hrl:59: illegal pattern
/usr/local/lib/erlang/lib/parsetools-2.1.7/include/yeccpre.hrl:60: variable 'Error' is unbound
/usr/local/lib/erlang/lib/parsetools-2.1.7/include/yeccpre.hrl:60: variable 'Stacktrace' is unbound
/usr/local/lib/erlang/lib/parsetools-2.1.7/include/yeccpre.hrl:63: variable 'Stacktrace' unsafe in 'try' (line 60)
/usr/local/lib/erlang/lib/parsetools-2.1.7/include/yeccpre.hrl:64: variable 'Error' unsafe in 'try' (line 60)
/usr/local/lib/erlang/lib/parsetools-2.1.7/include/yeccpre.hrl:64: variable 'Stacktrace' unsafe in 'try' (line 60)
could not compile dependency :dialyxir, "mix compile" failed. You can recompile this dependency with "mix deps.compile dialyxir", update it with "mix deps.update dialyxir" or clean it with "mix deps.clean dialyxir"
```

**Comment by denispeplin** [comment]
@907th, thanks for your explanation!
I've thought that `deps` have nothing to do with Erlang version, but removing `_build` didn't help. Only removing `deps` solved the compilation problem.

**Comment by jeremyjh** [comment]
I realize not everyone uses it but for what it is worth on circle we do not include any elixir code in the docker image, but we include _build in our cache and our cache key includes the version of elixir and OTP in it (statically). I would guess other CIs have similar features.

```yaml
      - save_cache:
          key: elixir166-otp203-cache1-{{ arch }}-{{ checksum "assets/package.json" }}-{{checksum "mix.lock"}}
          paths:
            - ~/.npm
            - ~/.cache/yarn
            - deps
            - _build
            - assets/node_modules
```
